apiVersion: v2
name: mysql-backup-chart
description: A Helm chart to create a cron job for MySQL backup
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: FathAlla Ebrahem
    email: fathalla.ebrahem22@gmail.com
