serviceAccount:
  enabled: true
  name: s3-restore-sa
  annotations: # Add any required annotations here
    eks.amazonaws.com/role-arn: <Role ARN>

bucket:
  name: <Bucket name>
  prefix: "mysql-backups" 
  region: "eu-west-1" # Specify the bucket region
  file: <File name>

database:
  type: "MySQL" # Specify the database type
  host: <Host URL>
  port: 3306
  name: <Database name>
  username: <Username> # Specify the MySQL username
  # kubectl create secret generic mysql-creds --from-literal=mysql-password=<Password> -n <Namespace>
  secretName: <Secret name>
  version: "8" # Specify the MySQL version (e.g., "5.7" or "8")


notifications:
  enabled: true
  method: teams
  teamsWebhookUrl: <Webhook URL>

project:
  name: "4UM" # Add your project name here

confluence:
  enabled: true
  pageTitle: <Page title>
  pageId: <Page ID>
  confluenceUrl: <Confluence URL>

volumes:
  - name: confluence-access-token
    secret:
      secretName: confluence-access-token
      items:
        - key: token
          path: access-token

volumeMounts:
  - name: confluence-access-token
    mountPath: /etc/confluence
    readOnly: true